### ISSUE TITLE
Dependency Uncomplete 

### ISSUE THREAD

**Issue by EgodPrime** [TimHe95/confTainter#1]
I used a brand new Ubuntu 20 to complete the compilation, which actually required the installation of libboost and zlib1g in addition to llvm10.0.

for libboost, the Cmake requires at least 1.73.0 , but actually 1.71.0 works well.

```bash
sudo apt install libboost1.71-all-dev
```
for zlib1g, just by typing

```bash
sudo apt install zlib1g-dev
```

**Comment by TimHe95** [comment]
err... sorry for that dependency, just remove if from makefile. Currently, no code depends on `libboost`.
